config/routes.rb
Rails.application.routes.draw do
  get 'search', to:"search#index"
  get 'postsaves/index'
  get 'admins/index'
  get 'comments/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }
  resources :posts do
    resources :comments
    get "publish/", to: "comments#publish"
    resources :likes
    get "create", to: "likes#create", as: :create_like

    resources :postsaves
    get "savepost", to: "postsaves#create", as: :create_order  
  end
    

  
  resources :admins do
    member do
      get :userprofile
      post :userpage
    end
    
  end
  root 'home#index'
  get "/home/ufile", to:"home#ufile"
  get "/home/yoga", to:"home#yoga"
  get "/home/food", to:"home#food"
  get "/home/historical",to:"home#historical"
  get "/home/userprofile", to: "home#profile"
  get "/home/userpage",to:"home#userpage"
  get "/home/usersave", to:"home#usersave"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/admins/index.html.erb
<% @user.each do |user|%>
<div class="card" style="width:38rem;padding :25px;margin-top:50px;margin-left:150px;">

 
  <div class="card-body">
      <p><%=link_to image_tag(user.image,class:"img-fluid rounded-circle border border-dark border-3",style:'width: 70px;margin-right:20px;'),userprofile_admin_path(user.id)%>
    <b> Posts: <%= user.posts.count%><span style="margin-right:20px"></span>
    Comments:<%=Comment.joins(:post).where(:posts => { :user_id => user.id}).count%>
    <%= link_to image_tag("/assets/deletepost.png",style: 'height:40px;width:40px;'),admin_path(user.id),data: { 
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
}%>

 
    </b></p>
    <h4 class="card-text"><%=user.username %></h4>
   

  </div>
 

</div>
<br>
<%end%>

app/views/admins/userpage.html.erb
<h1>dfvndf</h1>

app/views/admins/userprofile.html.erb
<%#= link_to image_tag("/assets/post.png",style: 'height:50px;width:50px;margin-left: 1075px;border-radius: 50%;'),new_post_path%>

  <div class="container h-50" style="margin-top:20px;">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-md-9 col-lg-7 col-xl-5">
        <div class="card" style="border-radius: 15px; background-color: #93e2bb;">
          <div class="card-body p-4 text-black">
            <div>
          
            </div>
            <div class="d-flex align-items-center mb-4">
              <div class="flex-shrink-0">
               <%=image_tag(@user.image,class:"img-fluid rounded-circle border border-dark border-3",style:'width: 70px;')%>
  
              </div>
              <div class="flex-grow-1 ms-3">
                <div class="d-flex flex-row align-items-center mb-2">
                  <p class="mb-0 me-2">@<%= @user.username %></p>
                  <ul class="mb-0 list-unstyled d-flex flex-row" style="color: #1B7B2C;">

                  </ul>
                </div>
                <div>
                <%a1 = @user.id%>
               
                  <p><%=link_to "user profile",home_ufile_url(a1)%>
                  <%# <a href="/admins/userpage" class="btn btn-outline-dark btn-rounded btn-sm"
                    data-mdb-ripple-color="dark">See profile</a>   %>
                     
            
                  
                </div>
              </div>
            </div>
            <hr>
            <p class="my-4 pb-1"><b>Posts: <%= @user.posts.count%></b>
            <b style="margin-left:25px;">Comments: <%=@cm %> </b></p>
            
           
        </div>
      </div>
    </div>
  </div>
 
           
<br>
<div class="row">
<% @post.each do |post|%>
  <div class="col-4">
<div class="card" style="width: 18rem;padding :25px;margin-top:50px;margin-left:80px;">

  <%=image_tag(post.file,style:'height:225px;width:250px;') %>
  <div class="card-body">
    <h5 class="card-title"><%=post.title %></h5>
    <p class="card-text"><%=post.content%></p>
    <p class="card-text text-primary">created by: <%=post.author%></p>
    
  <%= link_to image_tag("/assets/editpost.png",style: 'height:50px;width:50px;'), edit_post_path(post) %></li>
  <%= link_to image_tag("/assets/deletepost.png",style: 'height:35px;width:35px;'), post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  <%= link_to image_tag("/assets/comment1.png",style:'height:35px;width:35px;'),post_comments_path(post.id) %>
   
  </div>
 

</div>
<br>
</div>
<%end%>
</div>
<div style="margin-left:800px;margin-top:10px;">
  <%= paginate @post %>
</div>