config/routes.rb
Rails.application.routes.draw do
  get 'search', to:"search#index"
  get 'postsaves/index'
  get 'admins/index'
  get 'comments/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }
  resources :posts do
    resources :comments
    get "publish/", to: "comments#publish"
    resources :likes
    get "create", to: "likes#create", as: :create_like

    resources :postsaves
    get "savepost", to: "postsaves#create", as: :create_order  
  end
    

  
  resources :admins do
    member do
      get :userprofile
      post :userpage
    end
    
  end
  root 'home#index'
  get "/home/ufile", to:"home#ufile"
  get "/home/yoga", to:"home#yoga"
  get "/home/food", to:"home#food"
  get "/home/historical",to:"home#historical"
  get "/home/userprofile", to: "home#profile"
  get "/home/userpage",to:"home#userpage"
  get "/home/usersave", to:"home#usersave"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post

  validates :body, presence: true,length: { minimum: 10 ,maximum:100}
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
  def index
    if user_signed_in?
      @post = Post.find(params[:post_id])
      if @current_user.id == @post.user.id 

          @comment = @post.comments.all
      elsif  @current_user.admin? == true
          @comment = @post.comments.all
      else
          @comment= @post.comments.where(published:true)
      end
    else
      flash[:alert]= "please login first"
      redirect_to root_path
    end
    
  end
  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end
  def create
    @post = Post.find(params[:post_id])
    @comment = @post.comments.new(comment_params)
    
    if @comment.save
      SendNotificationMailer.create_notification(@comment).deliver_now
      redirect_to "/home/userpage"  
    else
      render :new, status: :unprocessable_entity
    end

   
  end

  def destroy
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    authorize! :destroy, @comment
    redirect_to post_comments_url, status: :see_other
  end

  def publish
   @comment = Comment.find(params[:format])
   @comment.update(published:true)
   flash[:alert]= "your comment is publish"
   redirect_to root_path
  end
  
  private
    def comment_params
      params.require(:comment).permit(:body)
    end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/index.html.erb
<% if user_signed_in?%>
<% @comment.each do |comment| %>

  <div class="card" style="width: 38rem;margin-top:10px;margin-left:150px;">
    <div class="card-body">

      <p class="card-text"><%= comment.body %>
    
      <%# if @current_user.id == @post.user.id%>
      <% if can? :destroy ,comment %>
      <%= link_to image_tag("/assets/deletepost.png",style: 'height:35px;width:35px;'), [comment.post, comment], data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %>
      <%end%>
      
      </p>
      
    </div>

  </div>

  <br>
<% end %>
<br>
<div>
<%= link_to "Add new", new_post_comment_path(@post.id) ,class:"btn btn-secondary",style:"width:100px;height:40px;margin-left:150px;margin-top:10px;"%>
</div>
<% else %>
  <p class="notice alert alert-info alert-dismissible fade show m-1"><%= notice%></p>
<% end %>

app/views/comments/new.html.erb
<div class='col-lg-6 mx-lg-auto'>
  <div class='card shadow' style="width: 25rem;">
    <div class='card-header'>
      <h2 class='card-title text-center'>Add Comments</h2>
    </div>
    <div class='card-body'>

    <%= form_with(model: [@post, @comment ], local:true)  do |form| %>
    <% if @comment.errors.any? %>
  <div id="error_explanation">
    <ul>
      <% @comment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

  <div>
    <%= form.label :body,"Comment" ,class:"form-group" %><br>
    <%= form.text_field :body ,class: "form-control form-control-lg mb-3"%>
  </div>

  <div class="actions text-center"><br>
    <%= form.submit class:'btn btn-lg btn-primary mb-4' %>
  </div>
<% end %>

    </div>
  </div>
</div>
<h1></h1>

app/views/comments/publish.html.erb
<h1>your comments is publish </h1>
<%=@comment %>
<%=@comment.id%>


<%=@post%>