config/routes.rb
Rails.application.routes.draw do
  get 'search', to:"search#index"
  get 'postsaves/index'
  get 'admins/index'
  get 'comments/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }
  resources :posts do
    resources :comments
    get "publish/", to: "comments#publish"
    resources :likes
    get "create", to: "likes#create", as: :create_like

    resources :postsaves
    get "savepost", to: "postsaves#create", as: :create_order  
  end
    

  
  resources :admins do
    member do
      get :userprofile
      post :userpage
    end
    
  end
  root 'home#index'
  get "/home/ufile", to:"home#ufile"
  get "/home/yoga", to:"home#yoga"
  get "/home/food", to:"home#food"
  get "/home/historical",to:"home#historical"
  get "/home/userprofile", to: "home#profile"
  get "/home/userpage",to:"home#userpage"
  get "/home/usersave", to:"home#usersave"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">

  <div class="container-fluid">
    <%= link_to "krishna" ,root_path, class:'navbar-brand'%>
   
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
      
        <% if user_signed_in?%>
        <li class="nav-item">
        <%= link_to "MyPost",home_userpage_url, class:'nav-link active'%>
        </li>
        <% if current_user.admin == true %>
        <li class="nav-item">
         <%= link_to "Users",admins_url, class:'nav-link active'%>
         <%# <a href="/admins" class='nav-link active' style="color:white;text-decoration: none;">All User</a> %>
         </li>
           
        <%end%>
        
<li class="nav-item">
<a href="/home/userprofile" class='nav-link active' style="color:white;text-decoration: none;margin-left:900px;">
<%=image_tag(current_user.image,style:'height:35%;width:35%;border-radius: 50%;')%>

</a> 
</li>
<li class="nav-item">
  <%=link_to "logout" ,destroy_user_session_path, data: {turbo_method: :delete},class:'nav-link active'%>
</li>


<% else%>

 <li class="nav-item" style="margin-left:970px;">
<%= link_to "login" ,new_user_session_path, class:'nav-link active justify-content-end'%>
<li class="nav-item">
<%= link_to "sign up",new_user_registration_path, class:'nav-link active justify-content-end'%>
</li>

<% end %>
        <li>
        
        
      </ul>
      
    </div>
  </div>
</nav>