config/routes.rb
Rails.application.routes.draw do
  get 'search', to:"search#index"
  get 'postsaves/index'
  get 'admins/index'
  get 'comments/index'
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    passwords: 'users/passwords',
    registrations: 'users/registrations',
    confirmations: 'users/confirmations',
  }
  resources :posts do
    resources :comments
    get "publish/", to: "comments#publish"
    resources :likes
    get "create", to: "likes#create", as: :create_like

    resources :postsaves
    get "savepost", to: "postsaves#create", as: :create_order  
  end
    

  
  resources :admins do
    member do
      get :userprofile
      post :userpage
    end
    
  end
  root 'home#index'
  get "/home/ufile", to:"home#ufile"
  get "/home/yoga", to:"home#yoga"
  get "/home/food", to:"home#food"
  get "/home/historical",to:"home#historical"
  get "/home/userprofile", to: "home#profile"
  get "/home/userpage",to:"home#userpage"
  get "/home/usersave", to:"home#usersave"


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @post = Post.where("published= true").order("created_at DESC").page params[:page]
  
  end

  def profile
    render template: "home/profile"
  end
  def usersave
    
    @savepost=Postsave.where("user_id=?",current_user).select(:post_id).distinct
    render template: "home/usersave"
  end
  def userpage
    @like=Like.joins(:post).where(:posts => { :user_id => current_user}).count

    @cm = Comment.joins(:post).where(:posts => { :user_id => current_user.id}).count
    @post = Post.where("user_id=?",current_user).order("created_at DESC").page params[:page]
    render template: "home/userpost"
  end
  def yoga
    @post=Post.where("category=?","yoga").order("created_at DESC").page params[:page]
    render template: "home/yoga"

  end
  def historical
    @post= Post.where("category=?","historical").order("created_at DESC").page params[:page]
    render template: "home/historical"

  end
  def food
    @post= Post.where("category=?","food").order("created_at DESC").page params[:page]
    render template: "home/food"

  end
  def ufile
    @user = User.find(params[:format])
    render template: "home/ufile"
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/food.html.erb
<h1>Food Blog</h1>
<% @post.each do |post| %>
  <div
    class="card"
    style="width: 18rem;padding :25px;margin-top:50px;margin-left:80px;"
  >

    <%= image_tag(post.file, style: "height:225px;width:250px;") %>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <p class="card-text text-primary">created by:<%= post.author %></p>

      <p>
      <%like = Like.find_by(users_id:current_user,post_id:post.id)%>
      
      <% if like.nil? == true %>
          <%=link_to image_tag("/assets/like2.png",style: "height:35px;width:35px;margin-right:10px;"),
          post_create_like_path(post.id)%>
      <%else%>
          <%=link_to image_tag("/assets/dislike2.png",style: "height:35px;width:35px;margin-right:10px;"),post_like_path(like.post.id,like), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure dislike?"
                } %>
      <%end%>
      <%= link_to image_tag("/assets/comment1.png", style: "height:35px;width:35px;"),
      post_comments_path(post.id) %>
      <% if can? :update, post %>
      <%= link_to image_tag("/assets/editpost.png",style: 'height:50px;width:50px;'), edit_post_path(post) %></li>
      <% end %>

      <% if can? :destroy, post %>
      <%= link_to image_tag("/assets/deletepost.png",style: 'height:35px;width:35px;'), post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
      <% end %>
      </p>
      <p>
      <b style="margin-left:10px;"><%=Like.where("post_id=?",post.id).count%></b>
      <b style="margin-left:40px;"><%=Comment.where("post_id=?",post.id).count%></b>
      </p>
      <p><%= link_to "All comments",post_comments_path(post.id),style:"color:Gray;text-decoration: none;" %></p>
     
       <p><%savepost = Postsave.where(user_id:current_user,post_id:post.id)%>
       
       <% if savepost.empty? == true %>
       
          <%= link_to image_tag("/assets/save.png",style: 'height:35px;width:35px;'),post_create_order_path(post.id) %>
       <%else%>
          <%postsave = savepost.ids.join.to_i%>
          <%a1=Postsave.find(postsave)%>
         <p><%#= image_tag("/assets/unsave.png",style: 'height:45px;width:45px;')%></p>
         <p><%= link_to image_tag("/assets/unsave.png",style: 'height:45px;width:45px;'),post_postsafe_path(a1.post.id,a1), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %></p>

       <% end %>
       </p>
    </div>

  </div>
<% end %>
<div style="margin-left:800px;margin-top:10px;">
  <%= paginate @post %>
</div>

app/views/home/historical.html.erb
<h1>Historical Blog</h1>
<% @post.each do |post| %>
  <div
    class="card"
    style="width: 18rem;padding :25px;margin-top:50px;margin-left:80px;"
  >

    <%= image_tag(post.file, style: "height:225px;width:250px;") %>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <p class="card-text text-primary">created by:<%= post.author %></p>

    <p>
      <%like = Like.find_by(users_id:current_user,post_id:post.id)%>
      
      <% if like.nil? == true %>
          <%=link_to image_tag("/assets/like2.png",style: "height:35px;width:35px;margin-right:10px;"),
          post_create_like_path(post.id)%>
      <%else%>
          <%=link_to image_tag("/assets/dislike2.png",style: "height:35px;width:35px;margin-right:10px;"),post_like_path(like.post.id,like), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure dislike?"
                } %>
      <%end%>
      <%= link_to image_tag("/assets/comment1.png", style: "height:35px;width:35px;"),
      post_comments_path(post.id) %>
      <% if can? :update, post %>
      <%= link_to image_tag("/assets/editpost.png",style: 'height:50px;width:50px;'), edit_post_path(post) %></li>
      <% end %>

      <% if can? :destroy, post %>
      <%= link_to image_tag("/assets/deletepost.png",style: 'height:35px;width:35px;'), post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
      <% end %>
      </p>
      <p>
      <b style="margin-left:10px;"><%=Like.where("post_id=?",post.id).count%></b>
      <b style="margin-left:40px;"><%=Comment.where("post_id=?",post.id).count%></b>
      </p>
      <p><%= link_to "All comments",post_comments_path(post.id),style:"color:Gray;text-decoration: none;" %></p>
     
       <p><%savepost = Postsave.where(user_id:current_user,post_id:post.id)%>
       
       <% if savepost.empty? == true %>
       
          <%= link_to image_tag("/assets/save.png",style: 'height:35px;width:35px;'),post_create_order_path(post.id) %>
       <%else%>
          <%postsave = savepost.ids.join.to_i%>
          <%a1=Postsave.find(postsave)%>
         <p><%#= image_tag("/assets/unsave.png",style: 'height:45px;width:45px;')%></p>
         <p><%= link_to image_tag("/assets/unsave.png",style: 'height:45px;width:45px;'),post_postsafe_path(a1.post.id,a1), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %></p>

       <% end %>
       </p>
    </div>

  </div>
<% end %>
<div style="margin-left:800px;margin-top:10px;">
  <%= paginate @post %>
</div>

app/views/home/index.html.erb
<div class="row" style="margin-top:50px;margin-left:100px;">

  <div class="col-4" ><a href="/home/yoga" class="btn btn-outline-secondary">Yoga</a>
  </div>
  <div class="col-4" ><a href="/home/food" class="btn btn-outline-secondary">Food</a>
  </div>
  <div class="col-4" ><a href="/home/historical" class="btn btn-outline-secondary">Historical</a>
  </div>
</div>

<% @post.each do |post| %>
  <div class="card" style="width: 18rem;padding :25px;margin-top:50px;margin-left:80px;">

    <%= image_tag(post.file, style: "height:225px;width:250px;") %>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <p class="card-text text-primary">created by:<%= post.author %></p>


      <p>
      

      <%like = Like.find_by(users_id:current_user,post_id:post.id)%>
      
      <% if like.nil? == true %>
          <%=link_to image_tag("/assets/like2.png",style: "height:35px;width:35px;margin-right:10px;"),
          post_create_like_path(post.id)%>
      <%else%>
          <%=link_to image_tag("/assets/dislike2.png",style: "height:35px;width:35px;margin-right:10px;"),post_like_path(like.post.id,like), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure dislike?"
                } %>
      <%end%>

      <%= link_to image_tag("/assets/comment1.png", style: "height:35px;width:35px;"),
      post_comments_path(post.id) %>
      <% if can? :update, post %>
      <%= link_to image_tag("/assets/editpost.png",style: 'height:50px;width:50px;'), edit_post_path(post) %></li>
      <% end %>

      <% if can? :destroy, post %>
      <%= link_to image_tag("/assets/deletepost.png",style: 'height:35px;width:35px;'), post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
      <% end %>
      </p>
      <p>
      <b style="margin-left:10px;"><%=Like.where("post_id=?",post.id).count%></b>
      <b style="margin-left:40px;"><%=Comment.where("post_id=?",post.id).count%></b>
      </p>
      <p><%= link_to "All comments",post_comments_path(post.id),style:"color:Gray;text-decoration: none;" %></p>
     
       <p><%savepost = Postsave.where(user_id:current_user,post_id:post.id)%>
       
       <% if savepost.empty? == true %>
       
          <%= link_to image_tag("/assets/save.png",style: 'height:35px;width:35px;'),post_create_order_path(post.id) %>
       <%else%>
          <%postsave = savepost.ids.join.to_i%>
          <%a1=Postsave.find(postsave)%>
         <p><%#= image_tag("/assets/unsave.png",style: 'height:45px;width:45px;')%></p>
         <p><%= link_to image_tag("/assets/unsave.png",style: 'height:45px;width:45px;'),post_postsafe_path(a1.post.id,a1), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %></p>

       <% end %>
       </p>
     
    </div>

  </div>
<% end %>
<div style="margin-left:800px;margin-top:10px;">
  <%= paginate @post %>
</div>

app/views/home/profile.html.erb
<a href="/users/edit"><%= image_tag ("/assets/update.jpeg"), style: 'height:30px;width:30px;float:right;margin-left: auto;border-radius: 50%;',class: "img-responsive"%></a>
<%= link_to image_tag("/assets/delete.jpeg",style: 'height:50px;width:50px;margin-left: 1075px;border-radius: 50%;'),registration_path(current_user),data: { 
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
}%>
                  



<section class="vh-100" style="background-color: #f4f5f7;">
  <div class="container  h-80">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom text-center text-white"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
            
                <%=image_tag(current_user.image,class:"img-fluid my-5",style:'height:50%;width:80%;border-radius: 50%;margin-top:25px',class: "img-responsive")%>
             
              <i class="far fa-edit mb-5"></i>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                 <h3><%= current_user.username %></h3>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  
             
                
                <div class="row pt-1">
        
                  <li class="contacts-block__item">
                    <i class="fa fa-birthday-cake" aria-hidden="true"></i>
                    <span><%= current_user.birth_date %></span>
                  </li>
                
                  <li class="contacts-block__item">
                   <i class="fa fa-envelope" aria-hidden="true"></i>
                    <span><%= current_user.email%></span>
                  </li>
                  <li class="contacts-block__item">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <span><%= current_user.contact %></span>
                  </li>
                  
                  <li class="contacts-block__item mb-0">
                    <i class="fa fa-adjust" aria-hidden="true"></i>
                    <span><%= current_user.address %></span>
                  </li>
                </ul>
                </div>
                
               
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/ufile.html.erb
<h2>user profile</h2>

<section class="vh-100" style="background-color: #f4f5f7;">
  <div class="container  h-80">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: .5rem;">
          <div class="row g-0">
            <div class="col-md-4 gradient-custom text-center text-white"
              style="border-top-left-radius: .5rem; border-bottom-left-radius: .5rem;">
            
                <%=image_tag(@user.image,class:"img-fluid my-5",style:'height:50%;width:80%;border-radius: 50%;margin-top:25px',class: "img-responsive")%>
             
              <i class="far fa-edit mb-5"></i>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                 <h3><%= @user.username %></h3>
                <hr class="mt-0 mb-4">
                <div class="row pt-1">
                  
             
                
                <div class="row pt-1">
        
                  <li class="contacts-block__item">
                    <i class="fa fa-birthday-cake" aria-hidden="true"></i>
                    <span><%= @user.birth_date %></span>
                  </li>
                
                  <li class="contacts-block__item">
                   <i class="fa fa-envelope" aria-hidden="true"></i>
                    <span><%= @user.email%></span>
                  </li>
                  <li class="contacts-block__item">
                    <i class="fa fa-phone" aria-hidden="true"></i>
                    <span><%= @user.contact %></span>
                  </li>
                  
                  <li class="contacts-block__item mb-0">
                    <i class="fa fa-adjust" aria-hidden="true"></i>
                    <span><%= @user.address %></span>
                  </li>
                </ul>
                </div>
                
               
                
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/userpost.html.erb
<a href="/posts/new"><%= image_tag ("/assets/newp.jpeg"), style: 'height:50px;width:50px;float:right;margin-left: auto;margin-top:10px;',class: "img-responsive"%></a>
<%#= link_to image_tag("/assets/post.png",style: 'height:50px;width:50px;margin-left: 1075px;border-radius: 50%;'),new_post_path%>

  <div class="container h-50" style="margin-top:20px;">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-md-9 col-lg-7 col-xl-5">
        <div class="card" style="border-radius: 15px; background-color: #93e2bb;">
          <div class="card-body p-4 text-black">
            <div>
          
            </div>
            <div class="d-flex align-items-center mb-4">
              <div class="flex-shrink-0">
               <%=image_tag(current_user.image,class:"img-fluid rounded-circle border border-dark border-3",style:'width: 70px;')%>
  
              </div>
              <div class="flex-grow-1 ms-3">
                <div class="d-flex flex-row align-items-center mb-2">
                  <p class="mb-0 me-2">@<%= current_user.username %></p>
                  <ul class="mb-0 list-unstyled d-flex flex-row" style="color: #1B7B2C;">

                  </ul>
                </div>
                <div>
                  <%# <a href="/posts/new" class="btn btn-outline-dark btn-rounded btn-sm"
                    data-mdb-ripple-color="dark">+ New Post</a> %>
                
                     <%# if @current_user.admin == true%>
                   <%# <a href="/admins" class="btn btn-outline-dark btn-rounded btn-sm"
                    data-mdb-ripple-color="dark">All user</a> %>
                     <%# end %>
                  
                </div>
              </div>
            </div>
            <hr>
            <p class="my-4 pb-1"><b>Posts: <%= current_user.posts.count%></b>
            <b style="margin-left:25px;">Comments: <%=@cm %> </b>
             <b style="margin-left:25px;">Likes: <%=@like %> </b></p>
            
           
        </div>
      </div>
    </div>
  </div>
 
           
<br>




<div class="row">
    <% @post.each do |post|%>
    <div class="col-4">
    <div class="card" style="width: 18rem;padding :25px;margin-top:50px;margin-left:80px;">

  <%=image_tag(post.file,style:'height:225px;width:250px;') %>
  <div class="card-body">
    <h5 class="card-title"><%=post.title %></h5>
    <p class="card-text"><%=post.content%></p>
    <p class="card-text text-primary">created by: <%=post.author%></p>
    
  <p>
  <%like = Like.find_by(users_id:current_user,post_id:post.id)%>
      
      <% if like.nil? == true %>
          <%=link_to image_tag("/assets/like2.png",style: "height:35px;width:35px;margin-right:10px;"),
          post_create_like_path(post.id)%>
      <%else%>
          <%=link_to image_tag("/assets/dislike2.png",style: "height:35px;width:35px;margin-right:10px;"),post_like_path(like.post.id,like), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure dislike?"
                } %>
      <%end%>
  <%= link_to image_tag("/assets/comment1.png",style:'height:35px;width:35px;'),post_comments_path(post.id) %>
  <%= link_to image_tag("/assets/editpost.png",style: 'height:50px;width:50px;'), edit_post_path(post) %></li>
  <%= link_to image_tag("/assets/deletepost.png",style: 'height:35px;width:35px;'), post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
  
   </p>
   <p>
      <b style="margin-left:10px;"><%=Like.where("post_id=?",post.id).count%></b>
      <b style="margin-left:40px;"><%=Comment.where("post_id=?",post.id).count%></b>
      </p>
  <p><%= link_to "All comments",post_comments_path(post.id),style:"color:Gray;text-decoration: none;" %></p>
  </div>
 
 
 </div>
    </div>
    <%end%>
</div>
<p><%= link_to "Back", :back %></p>

<div style="margin-left:800px;margin-top:10px;">
  <%= paginate @post %>
</div>

app/views/home/usersave.html.erb
<h1>Save Post</h1>
<%  @savepost.each do |post| %>
  <div
    class="card"
    style="width: 18rem;padding :25px;margin-top:50px;margin-left:80px;"
  >
 
   <%a1=Post.where(id:post.post_id)%>
   <%  a1.each do |post| %>
    <%= image_tag(post.file, style: "height:225px;width:250px;") %>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <p class="card-text text-primary">created by:<%= post.author %></p>
       <%savepost = Postsave.where(user_id:current_user,post_id:post.id)%>
       <%postsave = savepost.ids.join.to_i%>
          <%b1=Postsave.find(postsave)%>
      <p><%= link_to image_tag("/assets/unsave.png",style: 'height:45px;width:45px;'),post_postsafe_path(b1.post.id,b1), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %></p>
    </div>

   <%end%>
  

    <%#= image_tag(post.post_id.file, style: "height:225px;width:250px;") %>
    
  </div>
<% end %>

app/views/home/yoga.html.erb
<h1>Yoga Blog</h1>
<% @post.each do |post| %>
  <div
    class="card"
    style="width: 18rem;padding :25px;margin-top:50px;margin-left:80px;"
  >

    <%= image_tag(post.file, style: "height:225px;width:250px;") %>
    <div class="card-body">
      <h5 class="card-title"><%= post.title %></h5>
      <p class="card-text"><%= post.content %></p>
      <p class="card-text text-primary">created by:<%= post.author %></p>

     <p>
      <%like = Like.find_by(users_id:current_user,post_id:post.id)%>
      
      <% if like.nil? == true %>
          <%=link_to image_tag("/assets/like2.png",style: "height:35px;width:35px;margin-right:10px;"),
          post_create_like_path(post.id)%>
      <%else%>
          <%=link_to image_tag("/assets/dislike2.png",style: "height:35px;width:35px;margin-right:10px;"),post_like_path(like.post.id,like), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure dislike?"
                } %>
      <%end%>
      <%= link_to image_tag("/assets/comment1.png", style: "height:35px;width:35px;"),
      post_comments_path(post.id) %>
      <% if can? :update, post %>
      <%= link_to image_tag("/assets/editpost.png",style: 'height:50px;width:50px;'), edit_post_path(post) %></li>
      <% end %>

      <% if can? :destroy, post %>
      <%= link_to image_tag("/assets/deletepost.png",style: 'height:35px;width:35px;'), post_path(post), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>
      <% end %>
      </p>
      <p>
      <b style="margin-left:10px;"><%=Like.where("post_id=?",post.id).count%></b>
      <b style="margin-left:40px;"><%=Comment.where("post_id=?",post.id).count%></b>
      </p>
      <p><%= link_to "All comments",post_comments_path(post.id),style:"color:Gray;text-decoration: none;" %></p>
     
       <p><%savepost = Postsave.where(user_id:current_user,post_id:post.id)%>
       
       <% if savepost.empty? == true %>
       
          <%= link_to image_tag("/assets/save.png",style: 'height:35px;width:35px;'),post_create_order_path(post.id) %>
       <%else%>
          <%postsave = savepost.ids.join.to_i%>
          <%a1=Postsave.find(postsave)%>
         <p><%#= image_tag("/assets/unsave.png",style: 'height:45px;width:45px;')%></p>
         <p><%= link_to image_tag("/assets/unsave.png",style: 'height:45px;width:45px;'),post_postsafe_path(a1.post.id,a1), data: {
                  turbo_method: :delete,
                  turbo_confirm: "Are you sure?"
                } %></p>

       <% end %>
       </p>
    </div>

  </div>
<% end %>
<div style="margin-left:800px;margin-top:10px;">
  <%= paginate @post %>
</div>